spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.connection.characterEncoding: UTF-8
      hibernate.connection.useUnicode: true
  logging:
    level:
      root: INFO
      com.api: INFO
      org.hibernate.SQL: WARN
      org.hibernate.type.descriptor.sql.BasicBinder: WARN
      org.hibernate.orm: WARN
      org.springframework: INFO
      com.zaxxer.hikari: WARN
      org.springframework.security: INFO
    file:
      name: logs/dev.log
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

security:
  public-urls:
    - /api/v1/auth/**
  cors:
    allowed-origins:
      - http://localhost:4200
      - http://frontend

auth:
  cookie:
    secure: false

